name = "paymesh-webui"
main = ".vercel/output/static/_worker.js/index.js"
compatibility_date = "2024-12-01"

[assets]
directory = ".vercel/output/static"
binding = "ASSETS"

[vars]
RESEARCH_URL = "https://potential-fiesta-r9xxr77jww5h5xqp-7001.app.github.dev"
FRAMEGEN_URL = "https://potential-fiesta-r9xxr77jww5h5xqp-7002.app.github.dev"
